const memberInfo = [
  {
    id: 3,
    image: "./images/morocain-players/bono.jpg",
    name: "Yassine Bounou",
    position: "Goalkeeper",
    born: "September 17, 1993 (age 29 years), Paris, France",
    height: "1.95 m",
    nationality: "Canadian, Moroccan",
  },
  {
    id: 1,
    image: "./images/morocain-players/amrabet.jpg",
    name: "Sofyan Amrabat",
    position: "Midfielder",
    born: "August 21, 1996 (age 26 years), Huizen, Netherlands",
    height: "1.85 m",
    nationality: "Dutch, Moroccan",
  },
  {
    id: 2,
    image: "./images/morocain-players/bofal.jpeg",
    name: "Sofiane Boufal",
    position: "Attacking midfielder",
    born: "September 17, 1993 (age 29 years), Paris, France",
    height: "1.75 m",
    nationality: "French, Moroccan",
  },
  {
    id: 4,
    image: "./images/morocain-players/sais.jpeg",
    name: "Romain Saïss",
    position: "Centre-back defance",
    born: "March 26, 1990 (age 32 years), Bourg-de-Péage, France",
    height: "1.88 m",
    nationality: "French, Moroccan",
  },
  {
    id: 5,
    image: "./images/morocain-players/hakimi.jpg",
    name: "Achraf Hakimi",
    position: "Right-back defance",
    born: "November 4, 1998 (age 24 years), Madrid, Spain",
    height: "	1.81 m",
    nationality: "Dutch, Moroccan",
  },
  {
    id: 6,
    image: "./images/morocain-players/ziach.jpg",
    name: "Hakim Ziyech",
    position: "Attacking midfielder",
    born: "March 19, 1993 (age 29 years), Dronten ,Netherlands",
    height: "1.8 m",
    nationality: "Dutch, Moroccan",
  },
];

export default memberInfo;
